import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../components/layout/DarkMode/theme-provider";
import Header from "../components/layout/Header/page";
import { Sidebar } from "@/components/modern-side-bar";
import PageTransitionWrapper from "@/components/layout/AnimationBetweenPages/page";
import { Toaster } from "sonner"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "AQUA",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >

          <Header className="fixed top-0 left-0 w-full z-100" />

          <div className="flex min-h-screen">

          
            <div className=" container flex-1 md:ml-64 p-20 ">
      
                {children}
          
            </div>
          </div>

        </ThemeProvider>

        <Toaster richColors position="top-right" theme="system" />
      </body>
    </html>
  );
}
